services:
  homelab-web:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://homelab_app:homelab_app@192.168.20.14:5432/homelab
    networks:
      - npm

networks:
  npm:
    external: true
    name: br0.20